### PR TITLE
fix local addr to not be nil on dial

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
fixes #9

**Comment by jbenet** [comment]
@whyrusleeping you've tested this, right?

**Comment by whyrusleeping** [comment]
yeap, i tested it by integrating it into multiaddr and then using multiaddr to dial in my bandwidth benchmark from earlier.

**Comment by whyrusleeping** [comment]
multiaddr grabs the localaddr of the net.Conn for itself and panics without this change

**Pull request merged**
